# Generated by Django 4.0.3 on 2022-04-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='user',
            new_name='userqualification',
        ),
        migrations.AddField(
            model_name='qualification',
            name='datareference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datascraper'),
        ),
        migrations.AddField(
            model_name='website',
            name='dataprovider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datascraper'),
        ),
    ]
