# Generated by Django 4.0.3 on 2022-04-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='dataprovider',
        ),
    ]
