# Generated by Django 4.0.3 on 2022-04-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_website_dataprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascraper',
            name='dataprovider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.website'),
        ),
    ]
