# Generated by Django 4.0.4 on 2022-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsletter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='fullname',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
