# Generated by Django 4.0.4 on 2022-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_website_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='codecredential',
            field=models.TextField(null=True, unique=True),
        ),
    ]
