# Generated by Django 4.0.3 on 2022-04-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datascraper_dataprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='archiveQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isopportunity', models.BooleanField()),
                ('typeopportunity', models.TextField()),
                ('proposition', models.TextField(blank=True)),
                ('datequalification', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='archiveWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
