# Generated by Django 4.0.3 on 2022-04-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_archiveuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
