# Generated by Django 4.0.4 on 2022-04-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newsletter_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
