# Generated by Django 4.0.4 on 2022-04-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_website_number_alter_website_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascraper',
            name='titre',
            field=models.TextField(blank=True),
        ),
    ]
