# Generated by Django 4.0.3 on 2022-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_archivequalification_archivewebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='archiveCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('montant', models.TextField()),
                ('duree', models.TextField()),
                ('contactclient', models.TextField()),
                ('equipe', models.TextField()),
                ('proposition', models.TextField()),
                ('rapportfinal', models.TextField()),
                ('datecredential', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='archiveMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('datemission', models.DateField(null=True)),
            ],
        ),
    ]
