# Generated by Django 4.0.3 on 2022-04-17 14:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usermodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=api.models.upload_path),
        ),
    ]
