# Generated by Django 4.0.3 on 2022-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_archivecredentials_archivemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
