# Generated by Django 4.0.3 on 2022-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mission_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
