# Generated by Django 4.0.3 on 2022-04-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_codeauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datascraper',
            old_name='dateScraping',
            new_name='datescraping',
        ),
        migrations.RenameField(
            model_name='datascraper',
            old_name='originData',
            new_name='origindata',
        ),
        migrations.RenameField(
            model_name='datascraper',
            old_name='urlData',
            new_name='urldata',
        ),
    ]
