# Generated by Django 4.0.3 on 2022-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_archivecredentials_contactclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivecredentials',
            name='contactclient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archivecredentials',
            name='duree',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archivecredentials',
            name='equipe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archivecredentials',
            name='montant',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archivecredentials',
            name='proposition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archivecredentials',
            name='rapportfinal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archivecredentials',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='contactclient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='duree',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='equipe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='montant',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='proposition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='rapportfinal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
