# Generated by Django 4.0.3 on 2022-04-24 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_archivecredentials_contactclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='lastupdate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
