# Generated by Django 4.0.3 on 2022-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_credentials_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
