# Generated by Django 4.0.3 on 2022-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_credentials_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='newnotif',
            field=models.BooleanField(default=True),
        ),
    ]
