# Generated by Django 4.0.3 on 2022-04-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification_newnotif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='isopportunity',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='typeopportunity',
            field=models.TextField(blank=True),
        ),
    ]
